[build]
  command = "npm run clean && sass src:public/css && webpack --mode production"
  publish = "public"
  runtime = "node"

# Встановіть контекст для виробничого середовища (production)
[context.production]
  command = "npm run build"
  publish = "public"

# Ви можете додати інші налаштування, такі як змінні середовища, в залежності від потреб вашого проекту.
[build.environment]
 NODE_VERSION = "16"

[context.production.environment]
  NODE_ENV = "production"