[build]
  command = "npm run clean && sass src:public/css && webpack --mode production"
  publish = "public"
  runtime = "node"

# Встановіть контекст для виробничого середовища (production)
[context.production]
  command = "npm run build"
  publish = "public"


[context.production.environment]
  NODE_ENV = "production"